name: 'Cargo Semver Update and Tag'
branding:
  icon: 'at-sign'
  color: 'black'
description: 'Update Cargo.toml version with Semver #major #minor #patch, Then Tags and pushes the changes.'
inputs:
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
  GITHUB_REF:
    description: 'GITHUB_REF'
    required: true
outputs:
  new_version:
    description: 'new semver version'
  new_version_with_v:
    description: 'new semver version with v'
runs:
  using: 'composite'
  steps:
    - name: Checkout Source
      uses: actions/checkout@main
    - name: Cargo Semver Update
      uses: lemonxah/cargo_semver_update@v0.0.5
    - name: Verified commit
      uses: swinton/commit@v2.0.0
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      with:
        files: |
          Cargo.toml
        commit-message: Cargo.toml semver changed to ${{ steps.cargo.outputs.new_version }}
        ref: refs/heads/my-branch
    - name: Tag commit
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ inputs.GITHUB_TOKEN }}"
        tag: "${{ steps.cargo.outputs.new_version_with_v }}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.GITHUB_TOKEN }}
        branch: ${{ inputs.GITHUB_REF }}