name: 'Cargo Semver Update'
description: 'Update Cargo.toml version with Semver #major #minor #patch'
inputs:
outputs:
  new_version:
    description: 'new semver version'
  new_version_with_v:
    description: 'new semver version with v'
runs:
  using: 'composite'
  steps:
    - name: Checkout Source
      uses: actions/checkout@main
    - uses: Docker
      id: cargo
      image: 'Dockerfile'
    - name: Verified commit
      uses: swinton/commit@v2.0.0
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          Cargo.toml
        commit-message: Cargo.toml semver changed to ${{ stes.cargo.outputs.new_version }}
        ref: refs/heads/my-branch
    - name: Tag commit
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "${{ steps.cargo.outputs.new_version_with_v }}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}