name: 'Cargo Semver Update and Tag'
Icon: 'at-sign'
Color: 'black'
description: 'Update Cargo.toml version with Semver #major #minor #patch, Then Tags and pushes the changes.'
outputs:
  new_version:
    description: 'new semver version'
  new_version_with_v:
    description: 'new semver version with v'
runs:
  using: 'composite'
  steps:
    - name: Checkout Source
      uses: actions/checkout@main
    - name: Cargo Semver Update
      uses: lemonxah/cargo_semver_update@v0.0.3
    - name: Verified commit
      uses: swinton/commit@v2.0.0
      env:
        GH_TOKEN: ${{ github.token }}
      with:
        files: |
          Cargo.toml
        commit-message: Cargo.toml semver changed to ${{ steps.cargo.outputs.new_version }}
        ref: refs/heads/my-branch
    - name: Tag commit
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ github.token }}"
        tag: "${{ steps.cargo.outputs.new_version_with_v }}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ github.token }}
        branch: ${{ github.ref }}