name: 'Cargo Semver Update and Tag'
branding:
  icon: 'at-sign'
  color: 'black'
description: 'Update Cargo.toml version with Semver #major #minor #patch, Then Tags and pushes the changes.'
inputs:
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
runs:
  using: 'composite'
  steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
      - name: Cargo Semver Update
        id: update
        uses: lemonxah/cargo_semver_update@v1.0.3
      
      - name: Commit file
        uses: swinton/commit@v2.x
        env:
          GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        with:
          files: |
            Cargo.toml
          commit-message: Updating Cargo semver version to ${{ steps.update.outputs.new_version }}
        
      - name: Commit tagger
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: ${{ inputs.GITHUB_TOKEN }}
          tag: ${{ steps.update.outputs.new_version_with_v }}
